### ISSUE TITLE
With even the most basic example, I get a NullReferenceException when dragging

### ISSUE THREAD

**Issue by rabejens** [punker76/gong-wpf-dragdrop#224]
This is where I set up DND:

```xml
    <DataGrid ItemsSource="{Binding Sections, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type local:SectionsControl}}}" AutoGenerateColumns="False" CanUserAddRows="True" CanUserDeleteRows="True" SelectionMode="Single" CanUserSortColumns="False" dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True">
        <DataGrid.Columns>
            <DataGridTextColumn Header="Name" Binding="{Binding Name}" Width="*"/>
        </DataGrid.Columns>
    </DataGrid>
```

My `Section` object looks basic, too:

```C#
    public sealed class Section: ObservableObject {

        private string _name;

        public string Name {
            get { return _name; }
            set { Set("Name", ref _name, value); }
        }
    }
```
(I am using MVVM Light)

The `ItemsSource` is an `ObservableCollection` of my `Section` object.

Now, I can add sections to my `DataGrid` but when I try to drag them, I get a `NullReferenceException`.

What am I missing?

**Comment by punker76** [comment]
@rabejens Can you post the stacktrace of your exception? thx

**Comment by rabejens** [comment]
I only get the message that the exception was thrown in your DLL, no stacktrace.

**Comment by JArciaga** [comment]
I have a similar issue where I get a NullReferenceException.  When I move the object very quickly and release the mouse on top of the item I just selected, I get this exception:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at GongSolutions.Wpf.DragDrop.DropTargetInsertionAdorner.OnRender(DrawingContext drawingContext) in c:\Users\Jan\Documents\GitHub\gong-wpf-dragdrop\GongSolutions.Wpf.DragDrop\DropTargetInsertionAdorner.cs:line 32
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Documents.AdornerLayer.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Object reference not set to an instance of an object.
   at GongSolutions.Wpf.DragDrop.DropTargetInsertionAdorner.OnRender(DrawingContext drawingContext) in c:\Users\Jan\Documents\GitHub\gong-wpf-dragdrop\GongSolutions.Wpf.DragDrop\DropTargetInsertionAdorner.cs:line 32
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Documents.AdornerLayer.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by punker76** [comment]
@JArciaga I tried to fix this by changing the constructor of the DropTargetAdorner, so now the DragInfo is given via this contructor. I hope this fixes the OnRender issue. But it would be helpful if you can create a short repro app where you can demonstrate the issue. Thx /cc @rabejens
