### ISSUE TITLE
Dragging causes app crash in Server Core 2016 environment

### ISSUE THREAD

**Issue by shawnsmith2048** [punker76/gong-wpf-dragdrop#323]
The following exception occurs ONLY on Server CORE environments using a simple test app with just a Listview inside a Grid:

Application: DragDropTest.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IOleDropSource, Int32, Int32[])
   at System.Windows.OleServicesContext.OleDoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IOleDropSource, Int32, Int32[])
   at System.Windows.DragDrop.OleDoDragDrop(System.Windows.DependencyObject, System.Windows.DataObject, System.Windows.DragDropEffects)
   at System.Windows.DragDrop.DoDragDrop(System.Windows.DependencyObject, System.Object, System.Windows.DragDropEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DragSourceOnMouseMove(System.Object, System.Windows.Input.MouseEventArgs)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at DragDropTest.App.Main()

I paired down the example/test/repo project when I couldn't find anything regarding this scenario and was playing around with various options...but nothing worked to prevent the crash.

## What steps will reproduce this issue?

Restore NuGet package using repo link and and copy/deploy/run app on Server Core environment (if not building there).  Try to drag any of the ListView items around.  App crash occurs immediately.  The stack trace can be seen in the Windows Event Viewer.  Since it occurs on a Server Core environment, you will have to connect in with Windows Event Viewer from another non-Server Core machine to view the content.

### Expected outcome

Items are able to be dragged around without App Crash, just like in the non-Server Core environments.

### Repo

https://github.com/shawnsmith2048/DragDropTest

### Environment

- GongSolutions.WPF.DragDrop __v2.0.3
- Windows OS __Server Core 2016__
- Visual Studio __2017__
- .NET Framework __4.6.1 & 4.7.2__

**Comment by punker76** [comment]
@shawnsmith2048 It seems like that there is something restricted under the `Windows OS Server Core 2016`. How can I simply use a `Windows OS Server Core 2016`? Can I use a VM image? Where can I sownload such a image?

**Comment by shawnsmith2048** [comment]
@punker76, you can use any server core VM image.  Would you like me to create an image with the test app for you to download?

**Comment by punker76** [comment]
@shawnsmith2048 yes, that would be nice.

**Comment by punker76** [comment]
@shawnsmith2048 I really don't know what I should do here in this case. I use the official `System.Windows.DragDrop.DoDragDrop` method. This must ne an issue together with a VM or the OS or the installed Framework or whatever.

I’m closing this issue because it has been inactive for a few months. Maybe it's solved by yourself.

Thank you! 🙏

**Comment by leelds** [comment]
I System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 System.Windows.Controls.Primitives.Selector.InternalSelectedItemsStorage.Add(ItemInfo info)
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.ApplyCanSelectMultiple()
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   在 System.Windows.Controls.Primitives.Selector.set_CanSelectMultiple(Boolean value)
   在 System.Windows.Controls.ListBox.OnSelectionModeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   在 System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   在 GongSolutions.Wpf.DragDrop.Utilities.ItemsControlExtensions.SetSelectedItem(ItemsControl itemsControl, Object item) 位置 C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\Utilities\ItemsControlExtensions.cs:行号 319
   在 GongSolutions.Wpf.DragDrop.DragDrop.DoMouseButtonUp(Object sender, MouseButtonEventArgs e) 位置 C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\DragDrop.cs:行号 381
   在 GongSolutions.Wpf.DragDrop.DragDrop.DragSourceOnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e) 位置 C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\DragDrop.cs:行号 352
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by leelds** [comment]
The same....

**Comment by punker76** [comment]
@leelds It's not the same error as the original issue, but it seems like your issue will be fixed with the current source and the next release.

```
I System.ArgumentException: 已添加了具有相同键的项。
在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
在 System.Windows.Controls.Primitives.Selector.InternalSelectedItemsStorage.Add(ItemInfo info)
在 System.Windows.Controls.Primitives.Selector.SelectionChanger.ApplyCanSelectMultiple()
在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
在 System.Windows.Controls.Primitives.Selector.set_CanSelectMultiple(Boolean value)
在 System.Windows.Controls.ListBox.OnSelectionModeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
在 System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
在 GongSolutions.Wpf.DragDrop.Utilities.ItemsControlExtensions.SetSelectedItem(ItemsControl itemsControl, Object item) 位置 C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\Utilities\ItemsControlExtensions.cs:行号 319
```

**Comment by leelds** [comment]
@punker76 yeah,and what's time next release we can use ?
