### ISSUE TITLE
Try to catch an InvalidOperationException?

### ISSUE THREAD

**Issue by PatrickKursawe** [punker76/gong-wpf-dragdrop#469]
I know this is a poor report, but it is all information I have got - just a stacktrace.

InvalidOperationException: This Visual is not connected to a PresentationSource.
[GongSolutions.WPF.DragDrop]GongSolutions.Wpf.DragDrop.DragDrop/<>c
internal void <DoDragSourceMove>b__34_0(Point point);
IL Offset=0x0013. 
[GongSolutions.WPF.DragDrop]GongSolutions.Wpf.DragDrop.Utilities.MouseHelper/<>c__DisplayClass1_0
internal void <HookMouseMove>b__0(object _, EventArgs _);
IL Offset=0x0028. 
[...] skipping parts in Windows
[GongSolutions.WPF.DragDrop]GongSolutions.Wpf.DragDrop.DragDrop
private static void DoDragSourceMove(object sender, Func`2<class [PresentationCore]System.Windows.IInputElement,valuetype [WindowsBase]System.Windows.Point> getPosition);
IL Offset=0x01b8.
[GongSolutions.WPF.DragDrop]GongSolutions.Wpf.DragDrop.DragDrop
private static void DragSourceOnMouseMove(object sender, MouseEventArgs e);
IL Offset=0x007c. 

System is Windows 10.0.19045.0
The drag/drop operation is on a DataGrid inside an element host of a windows forms app.
       <DataGrid CanUserSortColumns="False" ItemsSource="{Binding Parameters}" Margin="0,0,0,0" x:Name="GrdParams" AutoGenerateColumns="False" 
                  SelectionUnit="FullRow"   SelectionMode="Extended" gong:DragDrop.IsDragSource="True" gong:DragDrop.IsDropTarget="True" 
                  gong:DragDrop.UseDefaultDragAdorner="True" gong:DragDrop.UseVisualSourceItemSizeForDragAdorner="True" CanUserAddRows="{Binding CanAddRemove}" CanUserDeleteRows="{Binding CanAddRemove}" >
           
As this error already happened a few times, but I really can't find a way to reproduce it at will, I would suggest that you maybe just catch this kind of exception in DoDragSource move and ignore the attempted operation?

I am using version 3.2.1 or your package. Thanks!

**Comment by PatrickKursawe** [comment]
Thanks for the hint, will do.

**Comment by PatrickKursawe** [comment]
Did it, and as the other user in #501 mentioned: It is an issue that happens occasionally and which at least I can't reproduce.
The suggested fix did not help that much, it turned my app from crashing into freezing.

`13:40:56.009 [Main UI]: Filtered unhandled dispatcher exception
13:40:56.009 [Main UI]: Exception of type InvalidOperationException, Message: This Visual is not connected to a PresentationSource., Stack:    at System.Windows.Media.Visual.PointFromScreen(Point point)
   at GongSolutions.Wpf.DragDrop.DragDrop.<>c.<DoDragSourceMove>b__34_0(Point point)
   at GongSolutions.Wpf.DragDrop.Utilities.MouseHelper.<>c__DisplayClass1_0.<HookMouseMove>b__0(Object _, EventArgs _)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

13:40:56.009 [Main UI]: Ignoring InvalidOperationException in drag source
13:40:56.009 [Main UI]: Exception of type InvalidOperationException, Message: This Visual is not connected to a PresentationSource., Stack:    at System.Windows.Media.Visual.PointFromScreen(Point point)
   at GongSolutions.Wpf.DragDrop.DragDrop.<>c.<DoDragSourceMove>b__34_0(Point point)
   at GongSolutions.Wpf.DragDrop.Utilities.MouseHelper.<>c__DisplayClass1_0.<HookMouseMove>b__0(Object _, EventArgs _)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DoDragSourceMove(Object sender, Func`2 getPosition)
`
