### ISSUE TITLE
InvalidOperationException: This Visual is not connected to a PresentationSource.

### ISSUE THREAD

**Issue by thorstenhuy** [punker76/gong-wpf-dragdrop#501]
**Describe the bug**

Occasionally, we get an *"InvalidOperationException: This Visual is not connected to a PresentationSource."* which crashes the application.
This was already reported as issue #469. The proposed fix was to use the *TryCatchOccurredException* method.
The proposed fix does not work.
The reason for this is that the exception occurs in the Dispatcher thread of the DispatcherTimer of *MouseHelper.cs* (line 19). The ty/catch in *DragDrop.DoDragSourceMove()* will therefore not catch the exception, and the *TryCatchOccurredException* method is never called.

```
2024-10-09 14:04:56,501 [  1] ERROR [(null)] App.HandleUnhandledException Unhandled exception
   at Common.LogHelper.AppendStackTrace(String message)
   at Common.LogHelper.ErrorWriteLine(Object obj, Object message, Exception ex)
   at UI.App.App.HandleUnhandledException(Object sender, Exception ex, Boolean shutdown)
   at UI.App.App.OnUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DoDragSourceMove(Object sender, Func`2 getPosition) in C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\DragDrop.cs:line 653
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at UI.App.App.Main()

System.InvalidOperationException: Dieses Visual-Objekt ist nicht mit einer "PresentationSource" verbunden.
   at GongSolutions.Wpf.DragDrop.Utilities.MouseHelper.<>c__DisplayClass1_0.<HookMouseMove>b__0(Object _, EventArgs _) in C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\Utilities\MouseHelper.cs:line 19
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by PatrickKursawe** [comment]
After having a quick look, I get the impression that the call that we'd need to wrap is in places like

DoDragSourceMove(sender, element => e.GetPosition(element));

the GetPosition call, or am I interpreting source and trace wrong here?

**Comment by PatrickKursawe** [comment]
Interesting...
https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.mouse.getposition?view=netframework-4.8#system-windows-input-mouse-getposition(system-windows-iinputelement)

Looking at the "remarks" section, it seems that using MouseEventArgs for e.GetPosition could be the problem, as this is officially discouraged here.

**Comment by tgadv** [comment]
We solved it like this:

`class MouseHelper`
```
        internal static void HookMouseMove(IDragSource dragHandler, Action<System.Windows.Point> mouseMoveHandler)
        {
            _timer = new System.Windows.Threading.DispatcherTimer(System.Windows.Threading.DispatcherPriority.Input);
            _timer.Tick += (_, _) =>
                {
                    try
                    {
                        if (TryGetCursorPos(out var lpPoint))
                        {
                            mouseMoveHandler?.Invoke(new System.Windows.Point(lpPoint.x, lpPoint.y));
                        }
                    }
                    catch (Exception ex)
                    {
                        if (!dragHandler.TryCatchOccurredException(ex))
                        {
                            throw;
                        }
                    }
                };
            _timer.Interval = new TimeSpan(1);
            _timer.Start();
        }
```

`class DragDrop`

```
MouseHelper.HookMouseMove(dragHandler, point =>
[...]
```

**Comment by PatrickKursawe** [comment]
Thanks. Any idea when there will be a release with this fix included?

**Comment by tgadv** [comment]
We're using our own fork. It seems like there's no maintainer around here at the time.

**Comment by punker76** [comment]
> We're using our own fork. It seems like there's no maintainer around here at the time.

I‘m here. In my spare time I try to fix things. You can create a PR instead a fork and we can discuss and test your solution. Thx

**Comment by tgadv** [comment]
> I‘m here. In my spare time I try to fix things. You can create a PR instead a fork and we can discuss and test your solution. Thx

Thanks for your nudge! I've created [PR 525](https://github.com/punker76/gong-wpf-dragdrop/pull/525) with our fix.
